"""Add the model columns no migration ever created (t_e7fbfe21).

Companion to 20261001_model_tables_parity, which creates the fourteen missing
tables. This covers the other half of the drift: eleven existing tables that
the ORM reads columns from which the migrated schema does not have.

Measured with backend/scripts/schema_drift_report.py against a database built
purely by `alembic upgrade head` — see backend/docs/SCHEMA_DRIFT.md for the
full analysis and the reasoning behind choosing "bring the chain up to the
model" over declaring the chain archival.

## The worst of them: admin_auth has no `email` column at all

Not a rarely-read column — `app/routers/auth.py` and
`app/routers/superadmin.py` filter admins by `AdminAuth.email` in 19 places,
and every admin is *created* with `email=` and `password_hash=` and never with
`admin_phone=`:

    app/routers/auth.py:369      AdminAuth(email=..., password_hash=..., ...)
    app/routers/superadmin.py:217  AdminAuth(email=..., password_hash=..., role=...)

The migrated `admin_auth` is keyed by `admin_phone VARCHAR(20) NOT NULL`
PRIMARY KEY and has no `email` and no `password_hash`. So on a clean build
every admin login raises `UndefinedColumnError: column admin_auth.email does
not exist`, and admin creation would fail the NOT NULL constraint on
`admin_phone`. Admin auth is entirely non-functional; it was masked because
production was grown by `create_all`, which had the columns.

This migration moves the primary key to the `id` UUID the model declares and
makes `admin_phone` nullable, which is what the model already says:

    admin_phone: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    id:          Mapped[uuid.UUID]     = mapped_column(UUID, primary_key=True, ...)

The swap is safe: no foreign key anywhere references admin_auth (verified
against information_schema), and no application code filters or joins on
`admin_phone` except the one legacy PIN-login path in auth.py:483, which reads
it as a filter and is unaffected by the PK no longer being on it.

## NOT NULL columns are added with a default, then the default is dropped

`plans.rotation_mode`, `posts.featured`, `orders.emails_sent` and friends are
`nullable=False` in the model but arrived late enough that migrations never
created them. ADD COLUMN NOT NULL fails on a table that already has rows, so
each is added with the model equivalent's default, backfilled implicitly, and
then has its server default dropped — leaving NOT NULL with no default, which
is exactly the model's shape and keeps the ORM as the sole source of truth for
the value.

## Deliberately NOT touched

  * Columns the migrated schema has but the model dropped (`dante_users`,
    `consent_events`, `referral_abuse_events`, `dante_port`,
    `alert_sent_*_pct_at`, `bunche_credential_id`). The drift here is
    model->database, not the reverse; dropping live columns to satisfy an
    autogenerated diff is destructive and is not this card's job.
  * `charon_escalations.initial_message` / `admin_phone`, which exist in the
    migrated schema but not the model. Extra columns are harmless; the ORM
    ignores them.
  * Index renames (`idx_bunche_cred_*` -> `idx_styxproxy_cred_*`).

Revision ID: 20261001_model_columns_parity
Revises: 20261001_model_tables_parity
Create Date: 2026-10-01 13:45:00.000000
"""

from alembic import op

# revision identifiers
revision = "20261001_model_columns_parity"
down_revision = "20261001_model_tables_parity"
branch_labels = None
depends_on = None

# (table, column, DDL type, DEFAULT clause or None, SET NOT NULL afterwards?)
# Kept as data rather than 40 near-identical op.execute calls so the whole
# shape of the drift is readable in one place.
_ADDED_COLUMNS: list[tuple[str, str, str, str | None, bool]] = [
    # admin_auth — see the module docstring for the PK swap.
    ("admin_auth", "id", "UUID", "gen_random_uuid()", True),
    ("admin_auth", "email", "VARCHAR(255)", None, False),
    ("admin_auth", "password_hash", "TEXT", None, False),
    ("admin_auth", "allowed_ips", "JSON", None, False),
    ("admin_invites", "feature_overrides", "JSON", None, False),
    ("charon_escalations", "customer_message", "TEXT", "''", True),
    ("charon_escalations", "resolved_at", "TIMESTAMP WITH TIME ZONE", None, False),
    ("charon_escalations", "updated_at", "TIMESTAMP WITH TIME ZONE", "now()", True),
    ("contact_submissions", "updated_at", "TIMESTAMP WITH TIME ZONE", "now()", True),
    ("customers", "referral_code", "VARCHAR(20)", None, False),
    ("free_trials", "styxproxy_credential_id", "INTEGER", None, False),
    ("orders", "tx_ref", "VARCHAR(100)", None, False),
    ("orders", "styxproxy_credential_id", "INTEGER", None, False),
    ("orders", "rotation_mode", "VARCHAR(20)", None, False),
    ("orders", "city_id", "INTEGER", None, False),
    ("orders", "city_name", "VARCHAR(100)", None, False),
    ("orders", "referral_tx_ref", "VARCHAR(100)", None, False),
    ("orders", "emails_sent", "INTEGER", "0", True),
    ("orders", "reminder_sent_at", "TIMESTAMP WITH TIME ZONE", None, False),
    ("orders", "idempotency_key", "VARCHAR(64)", None, False),
    ("orders", "customer_email", "VARCHAR(255)", None, False),
    ("plans", "price_per_gb", "NUMERIC(10, 2)", None, False),
    ("plans", "rotation_mode", "VARCHAR(20)", "'both'", True),
    ("plans", "supports_country_change", "BOOLEAN", "true", True),
    ("plans", "static_price_multiplier", "NUMERIC(4, 2)", "2.50", True),
    ("plans", "min_gb", "INTEGER", "5", True),
    ("plans", "max_gb", "INTEGER", "50", True),
    ("plans", "gb_tiers", "INTEGER[]", None, False),
    ("plans", "supports_city", "BOOLEAN", "false", True),
    ("posts", "featured", "BOOLEAN", "false", True),
    ("rls_policy", "using_clause", "TEXT", "'true'", False),
    ("rls_policy", "with_check", "TEXT", "'true'", False),
    ("rls_policy", "role_name", "VARCHAR(32)", "'styxproxy_app'", False),
    ("rls_policy", "policy_status", "VARCHAR(20)", "'not_started'", False),
    ("rls_policy", "created_by", "VARCHAR(120)", None, False),
    ("styxproxy_credentials", "socks_port", "INTEGER", None, False),
    ("styxproxy_credentials", "rotation_mode", "VARCHAR(20)", "'rotating'", True),
    ("styxproxy_credentials", "assigned_static_ip", "VARCHAR(45)", None, False),
    (
        "styxproxy_credentials",
        "assigned_static_session_id",
        "VARCHAR(50)",
        None,
        False,
    ),
    (
        "styxproxy_credentials",
        "last_static_assigned_at",
        "TIMESTAMP WITH TIME ZONE",
        None,
        False,
    ),
    ("styxproxy_credentials", "location_change_count", "INTEGER", "0", True),
    ("styxproxy_credentials", "rotation_mode_change_count", "INTEGER", "0", True),
    (
        "styxproxy_credentials",
        "location_changes_reset_at",
        "TIMESTAMP WITH TIME ZONE",
        None,
        False,
    ),
    (
        "styxproxy_credentials",
        "rotation_mode_changes_reset_at",
        "TIMESTAMP WITH TIME ZONE",
        None,
        False,
    ),
]


def _add_fk_if_absent(
    table: str, column: str, constraint: str, target: str
) -> None:
    """Add a foreign key only if the column has no outgoing FK yet.

    Guards on the column rather than the constraint name, because
    `Base.metadata.create_all` names constraints its own way and app/main.py
    runs it on every boot.
    """
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_name = '{table}'
                  AND kcu.column_name = '{column}'
            ) THEN
                ALTER TABLE {table}
                    ADD CONSTRAINT {constraint}
                    FOREIGN KEY ({column}) REFERENCES {target};
            END IF;
        END $$;
        """
    )


def upgrade() -> None:
    for table, column, col_type, default, not_null in _ADDED_COLUMNS:
        default_sql = f" DEFAULT {default}" if default else ""
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {col_type}{default_sql}"
        )

        if not_null:
            # Backfill before the NOT NULL lands, for tables that already hold
            # rows, then drop the server default so the ORM owns the value.
            # The WHERE guard keeps this from writing to rows a re-run (or
            # create_all) already populated with a real value.
            op.execute(
                f"UPDATE {table} SET {column} = {default} "
                f"WHERE {column} IS NULL"
            )
            op.execute(f"ALTER TABLE {table} ALTER COLUMN {column} SET NOT NULL")
            if default:
                op.execute(f"ALTER TABLE {table} ALTER COLUMN {column} DROP DEFAULT")

    # ── admin_auth: move the primary key from admin_phone to id ────────────
    # Both halves are needed: `id` only becomes a PK once admin_phone stops
    # being one, because a PK column is implicitly NOT NULL and the model
    # declares admin_phone nullable.
    op.execute("ALTER TABLE admin_auth DROP CONSTRAINT IF EXISTS admin_auth_pkey")
    op.execute("ALTER TABLE admin_auth ALTER COLUMN admin_phone DROP NOT NULL")
    op.execute("ALTER TABLE admin_auth ADD PRIMARY KEY (id)")

    # The model declares this unique index explicitly; without it two admins
    # could share an email and login would be ambiguous.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_auth_email ON admin_auth (email)"
    )

    # FKs the model declares, created after their targets (cities exists in the
    # previous revision).
    #
    # Postgres has no ADD CONSTRAINT IF NOT EXISTS, and the constraint name
    # create_all would have chosen is not necessarily ours — so guard on
    # "is there already an FK from this table on this column?" rather than on
    # the name. Re-running must not end up with two identical constraints.
    _add_fk_if_absent(
        "orders", "city_id", "fk_orders_city_id", "cities(id) ON DELETE SET NULL"
    )
    _add_fk_if_absent(
        "free_trials",
        "styxproxy_credential_id",
        "fk_free_trials_styxproxy_credential_id",
        "styxproxy_credentials(id)",
    )
    _add_fk_if_absent(
        "orders",
        "styxproxy_credential_id",
        "fk_orders_styxproxy_credential_id",
        "styxproxy_credentials(id)",
    )

    # Indexes the model declares on the newly added columns.
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_orders_tx_ref ON orders (tx_ref)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_orders_idempotency_key ON orders (idempotency_key)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_orders_referral_tx_ref ON orders (referral_tx_ref)"
    )


def downgrade() -> None:
    for table, column, _type, _default, _not_null in reversed(_ADDED_COLUMNS):
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS {column}")

    # Restore the original admin_auth primary key. Only meaningful if every row
    # has an admin_phone; rows created via email login will not, so this can
    # fail on a populated database — which is the correct refusal, as silently
    # dropping those rows would be worse.
    op.execute("ALTER TABLE admin_auth DROP CONSTRAINT IF EXISTS admin_auth_pkey")
    op.execute("ALTER TABLE admin_auth ADD PRIMARY KEY (admin_phone)")