name: Deploy to Staging

on:
  push:
    branches:
      - cpt-admin-ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Staging Deploy
        run: |
          curl -X POST \
            "https://api.vercel.com/v1/integrations/deploy/prj_goOuoWdAHd6YYdpzcZJEOl4Nkqea/KMgkjo72PJ"
