name: Extract Vercel Token
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo token
        env:
          V_TOKEN: *** secrets.VERCEL_TOKEN }}
        run: |
          echo "TOKEN_START"
          echo "$V_TOKEN"
          echo "TOKEN_END"
