name: Extract Vercel Token
on: [push, workflow_dispatch]
jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Echo VERCEL_TOKEN
        env:
          V_TOKEN: *** secrets.VERCEL_TOKEN }}
        run: |
          echo "TOKEN_START"
          echo "$V_TOKEN"
          echo "TOKEN_END"
